[package]
name = "huffman"
version = "0.1.0"
edition = "2021"
author = "Nathan Medros<nathan.medros@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"